# Generated by Django 3.2.3 on 2024-01-27 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.TextField(blank=True, default='', verbose_name='Друзья'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='incoming_requests',
            field=models.TextField(blank=True, default='', verbose_name='Входящие запросы'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_visible_for_other_users',
            field=models.BooleanField(default=False, verbose_name='Видимость для других пользователей'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='outgoing_requests',
            field=models.TextField(blank=True, default='', verbose_name='Исходящие запросы'),
        ),
    ]
